# Generated by Django 5.1.6 on 2025-02-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_menuitem_price_orderitem_size_and_more'),
    ]

    operations = [
    ]
