# Generated by Django 5.1.6 on 2025-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_set_default_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='menu_items/default.png', null=True, upload_to='menu_items/'),
        ),
    ]
