# Generated by Django 5.1.6 on 2025-02-28 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_menuitem_image'),
    ]

    operations = [
    ]
